from jukeboxcontroller import JukeboxController
dp = 70000
d_d = 40000
lp = 1200000
d_l = 50000
l_le = 280000
d_le = 280000

# Example reference patterns (you’ll need to measure your real ones)
known_patterns = {
    (dp, d_l , lp , l_le , dp): "A1",
    (dp, d_d, dp, d_l, lp, l_le, dp ): "A2",
    (dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp): "A3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp): "A4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp): "A5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp): "A6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp): "A7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp): "A8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp): "A9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp): "A10",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B1",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B2",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp): "B10",
    (dp, d_l, lp, l_le, dp, d_d, dp): "C1",
    (dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C2",
    (dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp): "C10",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D1",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D2",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp): "D10",
    (dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E1",
    (dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E2",
    (dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp): "E10",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F1",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F2",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp): "F10",
    (dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G1",
    (dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G2",
    (dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp): "G10",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp,
     d_d, dp, d_d, dp, d_d, dp): "H1",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_le, dp, d_d, dp, d_d, dp, d_d, dp): "H2",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp): "H3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp): "H4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp): "H5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp): "H6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp): "H7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp): "H8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp): "H9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d,dp): "H10",
    (dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J1",
    (dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J2",
    (dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_l, lp, l_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "J10",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K1",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K2",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K3",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K4",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K5",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K6",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K7",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K8",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K9",
    (dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp,
     d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp, d_le, dp, d_d, dp, d_d, dp, d_d, dp, d_d, dp): "K10",



}

controller = JukeboxController(
    pin=5,
    receiver_ip="192.168.1.73",
    receiver_port=5000,
    known_patterns=known_patterns
)

controller.run()
